### ISSUE TITLE
Isolated mode fails on OpenShift

### ISSUE THREAD

**Issue by gorkem** [microsoft/mindaro#116]
**Describe the bug**
When I try to use Bridge-to-Kubernetes with a deployment running on OpenShift it fails on isolated mode. 
 As far as I can see it fails because of the default RBAC on OpenShift when trying to read `namespaces`

```
2021-02-10T22:35:43.457Z | Common Extension Root    | ERROR | Error: connect-service-task-terminal-error <stack>Error: Failed to retrieve the namespaces: Error from server (Forbidden): namespaces is forbidden: User "...." cannot list resource "namespaces" in API group "" at the cluster scope\n\n	at t.KubectlClient.<anonymous> (/.../vscode/extensions/mindaro.mindaro-1.0.120210126/dist/extension.js:3:145260)\n	at Generator.throw (<anonymous>)\n	at s (/.../.vscode/extensions/mindaro.mindaro-1.0.120210126/dist/extension.js:3:140674)\n	at runMicrotasks (<anonymous>)\n	at processTicksAndRejections (internal/process/task_queues.js:97:5)</stack>
```

**To Reproduce**
I have used https://developers.redhat.com/developer-sandbox to make a deployment or a nodejs application. 
Used vscode to configure and launch debug.

**Comment by daniv-msft** [comment]
Thank you @gorkem for giving this scenario a try and opening this issue!
We're investigating OpenShift support, and I'm sharing this issue with the team member looking into it.
We might ask you more questions in the future, as there are some things that are not clear to me yet (for example, does OpenShift restrict listing namespaces by default but allows you to read from a particular one?).

We'll keep you updated once we have more info about this.

**Comment by squillace** [comment]
Note: whatever the solution ends up being, it should work for any cluster rbac'd like OS. This is just k8s, right?

**Comment by gorkem** [comment]
Correct. It is a common practice to limit namespace listing on multi-tenant environments.  We do have a way to remedy this issue on OpenShift using a resource called `projects` instead of namespace but let's cross that bridge when we get there. 

I hope listing the namespaces can be something optional.

**Comment by squillace** [comment]
Yup, see it all the time -- it's not an OS thing. We just need to have the extension be able to recognize when the user needs to do something, and work on a limited set when the user can't do something, and have the situation reported as well as possible.

**Comment by RJvH** [comment]
Following this issue. We're investigating the use of Brdige-to-Kubernetes to our Openshift clusters and experience the same issue.
@daniv-msft if you need information also from our side, feel free to contact me. Can you also keep me updated? Thanks!

**Comment by daniv-msft** [comment]
Thanks @RJvH for your comment. We've been working with @gorkem on a fix for this issue, that will be released in VS Code with our next release (early next week). We'll update this issue once the new bits are available!
