### ISSUE TITLE
Issue with Bridge to Kubernetes

### ISSUE THREAD

**Issue by rohitsoni77** [microsoft/mindaro#268]
Hey Folks,
5:53
I  want to use Bridge To Kubernetes extension to debug the Kubernetes cluster , when I make connection and try to start local version of service , the instance of the pod on the cluster crashes with the error : System.UnauthorizedAccessException: Access to the path '/proc/1/map_files' is denied.
 ---> System.IO.IOException: Operation not permitted
  --- End of inner exception stack trace ---
  at System.IO.Enumeration.FileSystemEnumerator`1.FindNextEntry(Byte* entryBufferPtr, Int32 bufferLength)
  at System.IO.Enumeration.FileSystemEnumerator`1.MoveNext()
  at System.IO.FileSystemWatcher.RunningInstance.AddDirectoryWatchUnlocked(WatchedDirectory parent, String directoryName)
  at System.IO.FileSystemWatcher.RunningInstance.AddDirectoryWatchUnlocked(WatchedDirectory parent, String directoryName)
  at System.IO.FileSystemWatcher.RunningInstance.AddDirectoryWatchUnlocked(WatchedDirectory parent, String directoryName)
  at System.IO.FileSystemWatcher.RunningInstance.AddDirectoryWatchUnlocked(WatchedDirectory parent, String directoryName)
  at System.IO.FileSystemWatcher.RunningInstance..ctor(FileSystemWatcher watcher, SafeFileHandle inotifyHandle, String directoryPath, Boolean includeSubdirectories, NotifyFilters notifyFilters, CancellationToken cancellationToken)
  at System.IO.FileSystemWatcher.StartRaisingEvents()
  at System.IO.FileSystemWatcher.StartRaisingEventsIfNotDisposed()
  at System.IO.FileSystemWatcher.set_EnableRaisingEvents(Boolean value)
  at Microsoft.Extensions.FileProviders.Physical.PhysicalFilesWatcher.TryEnableFileSystemWatcher()
  at Microsoft.Extensions.FileProviders.Physical.PhysicalFilesWatcher.CreateFileChangeToken(String filter)
  at Microsoft.Extensions.FileProviders.PhysicalFileProvider.Watch(String filter)
  at Microsoft.Extensions.Configuration.FileConfigurationProvider.<.ctor>b__1_0()
  at Microsoft.Extensions.Primitives.ChangeToken.ChangeTokenRegistration`1..ctor(Func`1 changeTokenProducer, Action`1 changeTokenConsumer, TState state)
  at Microsoft.Extensions.Primitives.ChangeToken.OnChange(Func`1 changeTokenProducer, Action changeTokenConsumer)
  at Microsoft.Extensions.Configuration.FileConfigurationProvider..ctor(FileConfigurationSource source)
  at Microsoft.Extensions.Configuration.Json.JsonConfigurationSource.Build(IConfigurationBuilder builder)
  at Microsoft.Extensions.Configuration.ConfigurationBuilder.Build()
  at Microsoft.Extensions.Hosting.HostBuilder.BuildAppConfiguration()
  at Microsoft.Extensions.Hosting.HostBuilder.Build()
  at Microsoft.BridgeToKubernetes.DevHostAgent.Program.CreateHost(String[] args) in /src/devhostagent/Program.cs:line 29
  at Microsoft.BridgeToKubernetes.Common.AspNetCoreRunner.RunHost(Assembly webhostAssembly, Func`2 hostBuilder, String[] args, String userAgent) in /src/common/AspNetCoreRunner.cs:line 32
5:54
I have set WORKDIR to a writable folder in the docker image , but still  it keeps on going to /proc/1/map_files , any suggestions as to how to resolve this

**Comment by wowq** [comment]
same issue

**Comment by wowq** [comment]
it should be work on add workingDir in pod.spec
